name: medsam
channels:
  - pytorch
  - nvidia
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.01.10=h06a4308_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.6.1.9=0
  - libcurand=10.3.2.106=0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.17=h5eee18b_0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libnpp=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.0=h6a678d5_2
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - lz4-c=1.9.4=h6a678d5_0
  - mkl=2023.1.0=h6d00ec8_46342
  - mkl_fft=1.3.6=py310h1128e8f_1
  - mkl_random=1.2.2=py310h1128e8f_1
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - numpy-base=1.24.3=py310hb5e798b_1
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1t=h7f8727e_0
  - pycparser=2.21=pyhd3eb1b0_0
  - python=3.10.11=h7a1cb2a_2
  - pytorch=2.0.0=py3.10_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - sqlite=3.41.2=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - torchtriton=2.0.0=py310
  - typing_extensions=4.5.0=py310h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
    - brotlipy==0.7.0
    - certifi==2023.5.7
    - cffi==1.15.1
    - contourpy==1.0.7
    - cryptography==39.0.1
    - cycler==0.11.0
    - filelock==3.9.0
    - fonttools==4.39.4
    - fsspec==2023.5.0
    - gmpy2==2.1.2
    - huggingface-hub==0.14.1
    - idna==3.4
    - imageio==2.28.1
    - jinja2==3.1.2
    - joblib==1.2.0
    - kiwisolver==1.4.4
    - lazy-loader==0.2
    - markupsafe==2.1.1
    - matplotlib==3.7.1
    - mkl-fft==1.3.6
    - mkl-random==1.2.2
    - mkl-service==2.4.0
    - monai==1.1.0
    - mpmath==1.2.1
    - networkx==2.8.4
    - nibabel==5.1.0
    - numpy==1.24.3
    - opencv-python==4.7.0.72
    - packaging==23.1
    - pandas==2.0.1
    - pillow==9.4.0
    - pip==23.0.1
    - pycocotools==2.0.6
    - pyopenssl==23.0.0
    - pyparsing==3.0.9
    - pysocks==1.7.1
    - python-dateutil==2.8.2
    - pytz==2023.3
    - pywavelets==1.4.1
    - pyyaml==6.0
    - requests==2.29.0
    - safetensors==0.3.1
    - scikit-image==0.20.0
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - setuptools==66.0.0
    - simpleitk==2.2.1
    - six==1.16.0
    - sympy==1.11.1
    - threadpoolctl==3.1.0
    - tifffile==2023.4.12
    - timm==0.9.2
    - torch==2.0.0
    - torchaudio==2.0.0
    - torchvision==0.15.0
    - tqdm==4.65.0
    - triton==2.0.0
    - typing-extensions==4.5.0
    - tzdata==2023.3
    - urllib3==1.26.15
    - wheel==0.38.4
prefix: /data/machong/software/anaconda3/envs/medsam
